# Generated by Django 3.2.18 on 2023-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20230328_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Published')], default=0),
        ),
    ]
