# Generated by Django 3.2.18 on 2023-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'original'), (1, 'edited'), (2, 'deleted')], default=0),
        ),
    ]
